### ISSUE TITLE
Select ALL

### ISSUE THREAD

**Issue by ivelt2** [ivelt2/ivelt2.github.io#4]
Need to add a select all on the category level

**Comment by KnaperYaden** [comment]
Brainstorming...

Adding something like this should work:
```
  <script language="JavaScript">
    function toggle(source) {
  checkboxes = document.getElementsByClassName('News');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
  </script>
```
With a new select item:
`<input type="checkbox" onClick="toggle(this)" onchange="updateUrl()" /> <b>וועל אויס אלע אין נייעס</b><br/>`

But this is only for one section (News class in the example). We need to adapt it to be per section (will probably need to wrap each section in a DIV and use the div class or something like it.

**Comment by ivelt2** [comment]
Fixed in current release
